version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravelnet

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravelnet

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_komwan
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge

volumes:
  dbdata:
